### ISSUE TITLE
no license

### ISSUE THREAD

**Issue by apotheon** [bolthar/freightrain#1]
I don't see any mention of a license under which this software is intended to be distributed.  I'd recommend one of the [OWL](http://owl.apotheon.org), the [MIT/X11 License](http://copyfree.org/licenses/mit/license.txt), or [the same license terms as Ruby](https://github.com/ruby/ruby/blob/trunk/BSDL).  Please add a LICENSE file indicating license terms.

**Comment by bolthar** [comment]
For the time being, I've added the Ruby license. Honestly, I don't know much about the whole issue - could you point me out to some (hopefully concise) resource so I can teach myself about the topic? That would be extremely helpful :-)

**Comment by apotheon** [comment]
Well . . . the [Copyfree Initiative](http://copyfree.org) site offers some information on various approaches to licensing.  Its explanations favor copyfree licenses, of course.  In particular, the [Copyfree Policy](http://copyfree.org/policy) section, plus the sections about copyright, copyleft, and public domain distribution policies (in the menu), describe some of the issues of various approaches.  A lengthy paean to [license simplicity](http://univacc.net/?page=license_simplicity) expresses some of my thoughts on the matter.  The short version is that copyfree licenses tend to be short and sweet (though not always), which is good for people reading licenses to see what they're allowed to do, and are also about as permissive as you can get so that people don't need to worry about bureaucratic requirements to jump through hoops when using the licensed work; copyleft licenses tend to be lengthy, full of special cases, and problematic for people who want to mix source from several different projects; trying to release something into the public domain can cause problems across jurisdictional lines and its validity is questionable; and of course closed source EULAs (and similar closed source licensing situations) tend to be really awful for people who want to be able to reuse others' libraries and source code.

I think your license choice is great.  It's not technically "the Ruby License", by the way.  Ruby, as of v1.9.3, is technically dual-licensed under the terms of the Simplified BSD License (the one you selected, also known as the 2-Clause BSD License or the FreeBSD License) and another license called the Ruby License, which I think is there only for the sake of historical interest.  By dual-licensed (in case you're not familiar with the term), I mean that people who use the software and redistribute it or otherwise deal in it can choose which license to use.  People using code from Ruby 1.9.3+ tend to either just keep the dual-licensing scheme or use the Simplified BSD License and discard the Ruby License.

My personal favorite license is the OWL (and I created it), for the simple fact that it's a fairly minimal license without giving up decent legal phrasing, much like the MIT/X11 License and Simplified BSD License, but at the same time it does not specifically refer to "software" as those other two licenses do.  I could imagine some possible issues arising if someone decided to be picky about legal terminology in a courtroom with regard to a software-specific license that is used to produce a non-software derivative work (such as a book, a desktop background image, and so on).  The likelihood of this occurring is pretty slim, I think, so it's probably far from the most important factor in license selection, though.

As I said, I like your license choice.  It's a short-and-sweet copyfree license, and I appreciate that.  I'll probably end up using freightrain in a Ruby project in the near future with that license choice.  If you want to discuss things any further, feel free to message me directly so we can take things to email or to pop into the freenode/##copyfree IRC channel (I hang out there a lot).

Thanks for clarifying the license terms.

**Comment by bolthar** [comment]
Hi Chad, sorry for the hugely late reply :-(

We can talk about this privately but (most likely due to my ignorance about github's interface) I don't know how to private message you. If you want to, feel free to contact me at andrea at andreadallera.com, i'd be very happy to hear from you.

Thanks for the primer on licensing, I'll delve into that in the near future!
